return {
	--'nvim-tree/nvim-tree.lua',
	--dependencies = {
		--'nvim-tree/nvim-web-devicons',
	--},
	--config = function()
		--require('nvim-tree').setup {
			--actions = {
				--open_file = {
					--quit_on_open = true,
				--},
			--},
			--sync_root_with_cwd = true,
			--respect_buf_cwd = true,
			--update_focused_file = {
				--enable = true,
			--},
			--view = {
				--width = 45,
				--side = 'left',
			--},
			--git = {
				--enable = true,
				--ignore = true,
			--},
			--filters = {
				--dotfiles = false,
			--},
		--}
	--end
}
